# Theme Settings Configuration File
##
### use settings.yml file for configure colors, ui, rtl, sidebar, animation options

### Main Settings
settings:
  skin: "light" # select initial skin option: "light" or "dark"

### Preloader
preloader:
  logo:
    image: "assets/img/logo80.png"
    alt: "Zoé Miller"

### Header
header:
  logo:
    image: "assets/img/logo80.png"
    alt: "Zoé Miller"



### Footer
footer:
  developer: "Developed by <strong>bslthemes</strong>"
  copyright: "<strong>Haides01</strong>. All rights reserved"

### Portfolio Filters Settings
portfolio:
  layout: "list" # select works layout options: "Grid" or "List"
  filters:
    - name: "FW"
      slug: "FW"
